name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["Build Pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from Build Pipeline
        uses: actions/download-artifact@v4
        with:
          name: build-info
          run-id: ${{ github.event.workflow_run.id }}
          path: ./

      - name: Display build-info.txt content
        run: |
          cat build-info.txt
